[package]
name = "boba"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.14.0"
regex = "1.10.4"
substring = "1.4.5"
derive_more = "0.99.17"
clap = { version = "4.5.4", features = ["derive"] }
ariadne = { version = "0.4.1", features = ["auto-color"] }
once_cell = "1.19.0"
