[package]
name = "boba-script"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["core", "parser", "lexer", "interpreter"]

[dependencies]
boba-script-core = { path = "./core" }
boba-script-parser = { path = "./parser" }
boba-script-lexer = { path = "./lexer" }
