[package]
name = "boba-script"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*", "interpreter"]

[dependencies]
boba-script-core = { path = "./crates/core" }
boba-script-parser = { path = "./crates/parser" }
boba-script-lexer = { path = "./crates/lexer" }
boba-script-ariadne = { path = "./crates/ariadne" }
