[package]
name = "boba-script-lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
unicode-segmentation = "1.10"
derive_more = { version = "1.0", features = ["display"] }
boba-script-ast.workspace = true
