[package]
name = "boba-script-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
derive_more = { version = "1.0", features = ["display"] }
boba-script-ast = { path = "../ast" }
