[package]
name = "boba-script-core"
version = "0.1.0"
edition = "2021"

[dependencies]
dashu = "0.4"
fxhash = "0.2"
indexmap = "2.2"
hashbrown = "0.14"
thiserror = "1.0"
derive_more = "0.99"
ptr-vec = { path = "../ptr-vec" }
